### ISSUE TITLE
Problem with RDF extension

### ISSUE THREAD

**Issue by exacs** [sparkica/LODRefine#19]
When click on "RDF > Edit RDF Skeleton..." appears the following error:

```
Uncaught TypeError: Cannot read property 'prefixes' of undefined
    at RdfSchemaAlignmentDialog._init (http://localhost:3333/extension/rdf-extension/scripts/rdf-schema-alignment.js:22:71)
    at new RdfSchemaAlignmentDialog (http://localhost:3333/extension/rdf-extension/scripts/rdf-schema-alignment.js:4:7)
    at Object.RdfExporterMenuBar.editRdfSchema (http://localhost:3333/extension/rdf-extension/scripts/menu-bar-extensions.js:53:2)
    at HTMLAnchorElement.click (http://localhost:3333/extension/rdf-extension/scripts/menu-bar-extensions.js:479:58)
    at HTMLAnchorElement.<anonymous> (http://localhost:3333/scripts/util/menu.js:178:22)
    at HTMLAnchorElement.dispatch (http://localhost:3333/externals/jquery-1.7.2.min.js:3:4816)
    at HTMLAnchorElement.i (http://localhost:3333/externals/jquery-1.7.2.min.js:3:709)
RdfSchemaAlignmentDialog._init @ rdf-schema-
rdf-schema-alignment.js:22 Uncaught TypeError: Cannot read property 'prefixes' of undefined(…)
RdfSchemaAlignmentDialog._init @ rdf-schema-alignment.js:22
RdfSchemaAlignmentDialog @ rdf-schema-alignment.js:4
RdfExporterMenuBar.editRdfSchema @ menu-bar-extensions.js:53
click @ menu-bar-extensions.js:479
(anonymous function) @ menu.js:178
dispatch @ jquery-1.7.2.min.js:3
i @ jquery-1.7.2.min.js:3
```

Happens with the following CSV file

[encuestas2014-csv.txt](https://github.com/sparkica/LODRefine/files/637473/encuestas2014-csv.txt)

**Comment by exacs** [comment]
This issue is the same as the pointed here https://github.com/sparkica/rdf-extension/issues/8
