### ISSUE TITLE
Windows Installation

### ISSUE THREAD

**Issue by erajabi** [sparkica/LODRefine#7]
How can I install LODrefine on windows, as I couldn't find the exe file in the folder? the refine path also doesn't work.

**Comment by elgamersitom** [comment]
Hi :),

I can't make LODRefine work, there is a file refine in the folder I downloaded from sourceforge but it doesn´t have any extension so windows don't recognize anything.

Some help?

**Comment by LukasSteindl** [comment]
Same problem here, how can we start this on windows?

**Comment by eliohb** [comment]
Hello LOD refine 1.0.8 don't have an .exe or .bat and the LODrefine 1.0.7 show the following error when i run it: 
10:37:23.470 [            rdf-extension] Initializing rdf extension (779ms)
10:37:23.470 [            rdf-extension] Initializing endpoint manager (0ms)
Exception in thread "main" java.lang.Error: class org.apache.lucene.index.IndexF
ormatTooOldException: org.apache.lucene.index.IndexFormatTooOldException: Format
 version is not supported (resource: ChecksumIndexInput(SimpleFSIndexInput(path=
"C:\Users\hbeich\AppData\Roaming\Google\Refine\cache\rdfExtension\export\luceneI
ndex\segments_7"))): 1071082519 (needs to be between -1 and -11). This version o
f Lucene only supports indexes created with release 1.9 and later.
        at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:17
77)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:183)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:24
7)
        at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:66)

        at org.mozilla.javascript.gen.c10._c4(file:/C:/Users/hbeich/Desktop/lodr
efine-1.0.7.1/webapp/extensions/rdf-extension/module/MOD-INF/controller.js:103)
        at org.mozilla.javascript.gen.c10.call(file:/C:/Users/hbeich/Desktop/lod
refine-1.0.7.1/webapp/extensions/rdf-extension/module/MOD-INF/controller.js)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:3
98)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:306
5)
        at org.mozilla.javascript.gen.c10.call(file:/C:/Users/hbeich/Desktop/lod
refine-1.0.7.1/webapp/extensions/rdf-extension/module/MOD-INF/controller.js)
        at edu.mit.simile.butterfly.ButterflyModuleImpl.scriptInit(ButterflyModu
leImpl.java:636)
        at edu.mit.simile.butterfly.ButterflyModuleImpl.init(ButterflyModuleImpl
.java:94)
        at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:47
6)
        at edu.mit.simile.butterfly.Butterfly.configure(Butterfly.java:451)
        at edu.mit.simile.butterfly.Butterfly.init(Butterfly.java:308)
        at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.jav
a:440)
        at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:26
3)
        at com.google.refine.RefineServer.configure(Refine.java:289)
        at com.google.refine.RefineServer.init(Refine.java:203)
        at com.google.refine.Refine.init(Refine.java:116)
        at com.google.refine.Refine.main(Refine.java:110)
